In [1]:
import pandas as pd 
df = pd.read_csv("insurance.csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

### Data Preparation

In [2]:
df.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [3]:
df['region'].unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [4]:
df['sex'] = df['sex'].replace({'female': 1, 'male': 2})
df['smoker'] = df['smoker'].replace({'yes': 1, 'no': 2})
df['region'] = df['region'].replace({'southwest': 1, 'southeast': 2, 'northwest': 3, 'northeast': 4})

### Defining Input Features and Target Variable

In [5]:
X = df.drop(columns = ['charges'])
y = df['charges']

In [6]:
X

      age  sex     bmi  children  smoker  region
0      19    1  27.900         0       1       1
1      18    2  33.770         1       2       2
2      28    2  33.000         3       2       2
3      33    2  22.705         0       2       3
4      32    2  28.880         0       2       3
...   ...  ...     ...       ...     ...     ...
1333   50    2  30.970         3       2       3
1334   18    1  31.920         0       2       4
1335   18    1  36.850         0       2       2
1336   21    1  25.800         0       2       1
1337   61    1  29.070         0       1       3

[1338 rows x 6 columns]

In [7]:
y

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

### Split for Training and Testing

In [8]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state = 1)

### Scaling the Data

In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaler = scaler.fit_transform(X_train)
X_test_scaler = scaler.transform(X_test)

### Model Development and Evaluation

In [10]:
from sklearn.linear_model import LinearRegression

from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree=3)

poly_features_xtrain = poly.fit_transform(X_train_scaler)

poly_features_xtest = poly.transform(X_test_scaler)

lin = LinearRegression()

lin.fit(poly_features_xtrain ,  y_train)

LinearRegression()

In [11]:
y_pred = lin.predict(poly_features_xtest)

In [12]:
from sklearn.metrics import mean_absolute_error  #error of test
mean_absolute_error(y_test, y_pred)

2767.1383628358208

In [13]:
y_pred_train = lin.predict(poly_features_xtrain)

In [14]:
mean_absolute_error(y_train, y_pred_train) #error of rain

2765.397715662014

In [18]:
from sklearn.metrics import r2_score

r2_test = r2_score(y_test, y_pred)
r2_train = r2_score(y_train, y_pred_train)

print("R2 Test Score:", r2_test)
print("R2 Train Score:", r2_train)

R2 Test Score: 0.8358338288523669
R2 Train Score: 0.855853778012363

In [15]:
##The closer MAE is to 0, the more accurate the model is